/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopfinalkelompokb;

import java.util.Scanner;

public class App {
    // public String getGreeting() {
    //     return "Hello World!";
    // }

    static Scanner input = new Scanner(System.in);

    public static void main(String[] args) {
        double r, luas, keliling;
        
        System.out.println("Luas dan Keliling Lingkaran");
        System.out.println("");
        System.out.println("Masukan nilai jari-jari : ");
        
        r = input.nextDouble();
        luas = 3.14 * r * r;
        keliling = 2 * 3.14 * r;
        
        System.out.println("HASIL");
        System.out.println("Luas : " + luas);
        System.out.println("Keliling : " + keliling);
    }
}
